package com.kiacms.notification.enums;

public enum NotificationType {
    APPROVAL_RESULT,
    ROLE_UPGRADE_RESULT,
    SESSION_ZOOM_UPDATED,
    SESSION_RECORDING_UPDATED,
    SESSION_SUMMARY_UPDATED,
    NOTE_TAGGED,
    NOTE_COMMENTED,
    PROJECT_APPLICATION_RECEIVED,
    PROJECT_APPLICATION_RESULT,
    MENTOR_APPLICATION_RECEIVED,
    MENTOR_APPLICATION_RESULT,
    PROJECT_DELETED_BY_ROOT,
    PROJECT_AI_RECOMMENDED,
    SYSTEM_ANNOUNCEMENT
}
